import { 
  faPlus, 
  faXmark, 
  faImage, 
  faSave, 
  faBars,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faHeart,
  faUser,
  faComment,
  faEye,
  faEyeSlash,
  faCircleInfo,
  faStar,
  faBookOpen,
  faBell,
  faCheckCircle,
  faFire,
  faShield,
  faAward,
  faLifeRing,
  faQuestionCircle,
  faCheck,
  faClock,
  faPaperPlane,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faMinus,
  faSearch,
  faShare,
  faEnvelope,
  faLink,
  faSun,
  faMoon,
  faHome,
  faPlayCircle,
  faHeadphones,
  faThumbsUp,
  faRotate,
  faLock,
  faCreditCard,
  faBitcoinSign,
  faGauge,
  faList,
  faGear,
  faArrowRightFromBracket,
  faFilter,
  faUserCircle,
  faTag,
  faClipboardList,
  faCube,
  faChartBar,
  faDollarSign,
  faTrash
} from "@fortawesome/free-solid-svg-icons";

// Map icon names to FontAwesome icons
export const iconMap: Record<string, any> = {
  HamburgerIcon: faBars,
  XIcon: faXmark,
  ChevronDownIcon: faChevronDown,
  ChevronRightIcon: faChevronRight,
  ChevronUpIcon: faChevronUp,
  HeartIcon: faHeart,
  UserIcon: faUser,
  ChatIcon: faComment,
  EyeIcon: faEye,
  EyeSlashIcon: faEyeSlash,
  InformationCircleIcon: faCircleInfo,
  StarIcon: faStar,
  BookOpenIcon: faBookOpen,
  BellIcon: faBell,
  CheckCircleIcon: faCheckCircle,
  FireIcon: faFire,
  ShieldCheckIcon: faShield,
  AwardIcon: faAward,
  LifebuoyIcon: faLifeRing,
  VerifiedIcon: faShield,
  QuestionMarkCircleIcon: faQuestionCircle,
  CheckmarkIcon: faCheck,
  ClockIcon: faClock,
  SendIcon: faPaperPlane,
  SparklesIcon: faStar,
  ArrowLeftIcon: faArrowLeft,
  ArrowRightIcon: faArrowRight,
  ArrowUpIcon: faArrowUp,
  PlusIcon: faPlus,
  MinusIcon: faMinus,
  SearchIcon: faSearch,
  ShareIcon: faShare,
  MailIcon: faEnvelope,
  LinkIcon: faLink,
  SunIcon: faSun,
  MoonIcon: faMoon,
  HomeIcon: faHome,
  PlayCircleIcon: faPlayCircle,
  HeadphoneIcon: faHeadphones,
  ThumbsUpIcon: faThumbsUp,
  RefreshIcon: faRotate,
  LockClosedIcon: faLock,
  CreditCardIcon: faCreditCard,
  CurrencyBitcoinIcon: faBitcoinSign,
  DashboardIcon: faGauge,
  OrderHistoryIcon: faList,
  SettingsIcon: faGear,
  LogoutIcon: faArrowRightFromBracket,
  FilterIcon: faFilter,
  InstagramProfileIcon: faUserCircle,
  TagIcon: faTag,
  ClipboardDocumentListIcon: faClipboardList,
  CubeIcon: faCube,
  CogIcon: faGear,
  ChartIcon: faChartBar,
  CurrencyDollarIcon: faDollarSign,
  PhotoIcon: faImage,
  FollowersIcon: faUser,
  LikesIcon: faHeart,
  ViewsIcon: faEye,
  AutomaticLikesIcon: faHeart,
  TikTokFollowersIcon: faUser,
  TikTokViewsIcon: faEye,
  YouTubeSubscribersIcon: faUser,
  YouTubeLikesIcon: faThumbsUp,
  YouTubeViewsIcon: faEye,
  RocketLaunchIcon: faFire,
  InstagramLikesShortcutIcon: faHeart,
  InstagramViewsShortcutIcon: faEye,
  InstagramFollowersShortcutIcon: faUser,
  TikTokLikesShortcutIcon: faHeart,
  TikTokFollowersShortcutIcon: faUser,
  YouTubeLikesShortcutIcon: faThumbsUp,
  YouTubeSubscribersShortcutIcon: faUser,
  YouTubeViewsShortcutIcon: faEye,
};
